require:
  - rubocop-rspec

AllCops:
  Exclude:
    - vendor/**/*

Layout/LineLength:
  Max: 100

Metrics/AbcSize:
  Exclude:
    - spec/lib/eac_launcher/ruby/gem/build_spec.rb
    - spec/lib/eac_launcher/stereotypes/git_subrepo/publish_spec.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - spec/spec_helper/eac_launcher.rb

RSpec:
  Exclude:
    - spec/lib/eac_launcher/**/*

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
